language: go

go:
    - 1.4
    - tip

env:
    - GOMAXPROCS=2

install:
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - go vet ./...
    - go test -v -race ./...
    - goveralls -package=api -service=travis-ci